apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs001
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs"
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: {{ .Values.volume.server }}
    path: /mnt/share/